version: '3.8'

services:
  db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: ABCDabcd00..
        MYSQL_DATABASE: ibtissam
      ports:
        - "3307:3306"
      networks:
        - spring-network
      depends_on:
        - backend
  backend:
    build:
      context: ./ibtissam-bank
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ibtissam
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ABCDabcd00..
    networks:
      - spring-network

  frontend:
    build:
      context: ./my-banking-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - spring-network


networks:
    spring-network:
        external: true

    
