name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t attoba/secure_online_banking:latest .

    # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push attoba/secure_online_banking:latest
        
    # Step 4: Run Tests (Backend)
      - name: Run backend tests
        working-directory: ./ibtissam-bank
        run: ./mvnw test

    # Step 5: Run Tests (Frontend)
      - name: Run frontend tests
        working-directory: ./my-banking-app
        run: npm install && npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      run: |
        docker-compose -f docker-compose.yml up -d
