name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: List files
        run: ls -R    

    # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

     # Step 3: Build Docker Image (Backend)
      - name: Build Backend Docker Image
        run: docker build -t attoba/backend-image:latest -f ./ibtissam-bank/Dockerfile ./ibtissam-bank 

    # Step 4: Push Backend Docker Image to Docker Hub
      - name: Push Backend Docker Image
        run: docker push attoba/backend-image:latest

    # Step 5: Build Docker Image (Frontend)
      - name: Build Frontend Docker Image
        run: docker build -t attoba/frontend-image:latest -f ./my-banking-app/Dockerfile ./my-banking-app 

    # Step 6: Push Frontend Docker Image to Docker Hub
      - name: Push Frontend Docker Image
        run: docker push attoba/frontend-image:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Step 3: Create the external network if not exists
    - name: Create external network
      run: |
        docker network ls | grep spring-network || docker network create spring-network
        
    - name: Deploy to production
      run: docker-compose -f ./docker-compose.yml up -d
        #docker-compose -f /home/runner/work/SecureBanking-fullapp/docker-compose.yml up -d
